### ISSUE TITLE
Broken paths when attempting to build, either that or README needs more than just npm install

### ISSUE THREAD

**Issue by emudojo** [epixa/tbyn#1]
webpack is missing from the initial npm install and when I try to do npm run-script dev or webpack

I receive several errors

ERROR in ./src/reducers/payees.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../lib/data/payees in C:\www\tbyn/src\reducers
 @ ./src/reducers/payees.js 8:14-46

ERROR in ./src/reducers/transactions.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../lib/data/payees in C:\www\tbyn/src\reducers
 @ ./src/reducers/transactions.js 16:14-46

ERROR in ./src/reducers/transactions.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../lib/data/transactions in C:\www\tbyn/src\reducers
 @ ./src/reducers/transactions.js 18:20-58

ERROR in ./src/components/workarea/index.css
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../node_modules/css-loader/index.js in C:\www\tbyn/src\components\workarea
 @ ./src/components/workarea/index.css 4:14-82 13:2-17:4 14:20-88

ERROR in ./src/components/workarea/index.css
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../node_modules/style-loader/addStyles.js in C:\www\tbyn/src\components\workarea
 @ ./src/components/workarea/index.css 7:13-74

ERROR in ./src/components/sidebar/index.css
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../node_modules/css-loader/index.js in C:\www\tbyn/src\components\sidebar
 @ ./src/components/sidebar/index.css 4:14-82 13:2-17:4 14:20-88

ERROR in ./src/components/sidebar/index.css
Module not found: Error: Cannot resolve 'file' or 'directory' ./../../../node_modules/style-loader/addStyles.js in C:\www\tbyn/src\components\sidebar
 @ ./src/components/sidebar/index.css 7:13-74

ERROR in ./src/containers/navigation/off-budget-account.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../lib/data/accounts in C:\www\tbyn/src\containers\navigation
 @ ./src/containers/navigation/off-budget-account.js 9:16-53

ERROR in ./src/containers/navigation/budget-account.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../lib/data/accounts in C:\www\tbyn/src\containers\navigation
 @ ./src/containers/navigation/budget-account.js 9:16-53

ERROR in ./src/containers/navigation/closed-account.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../lib/data/accounts in C:\www\tbyn/src\containers\navigation
 @ ./src/containers/navigation/closed-account.js 9:16-53

ERROR in ./src/containers/navigation/account/nav.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../../lib/data/transactions in C:\www\tbyn/src\containers\navigation\account
 @ ./src/containers/navigation/account/nav.js 9:20-64

ERROR in ./src/containers/navigation/account/link.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../../lib/data/transactions in C:\www\tbyn/src\containers\navigation\account
 @ ./src/containers/navigation/account/link.js 9:20-64
webpack: bundle is now VALID.

just to name a few

**Comment by epixa** [comment]
@emudojo What version of npm are you using?  This has only been tested with node 6/npm 3 so far, and webpack is listed as a dev dependency: https://github.com/epixa/tbyn/blob/master/package.json#L63

**Comment by emudojo** [comment]
<img src='https://i.imgur.com/93q5oqb.png' />

Same error when trying build

**Comment by epixa** [comment]
Both the npm and node version you're using are unsupported for this project.  I doubt the node version really matters, but I've only ever tested it with node 6, and I don't really intend to support anything below that.  I do intend to support npm 4 though, though I haven't had time to test it out and make sure it all works.  It looks like it doesn't!

If you need npm 4 support right now, then I welcome pull requests.  Otherwise, I will get the project compatible with npm 4 eventually.

**Comment by emudojo** [comment]
it is NOT NPM or NODE, I used the exact same versions but in ubuntu and 
compiled without issues

It is certainly windows not friendly, although I was expecting a little 
more than just a shell of a project, nevertheless is a good start I'll 
see if I can create a fork and contribute with a few things.

------ Mensaje original ------
De: "Court Ewing" <notifications@github.com>
Para: "epixa/tbyn" <tbyn@noreply.github.com>
CC: "Hertzel Armengol Rivera" <hertzel@polygonize.com>; "Mention" 
<mention@noreply.github.com>
Enviado: 4/1/2017 01:02:57
Asunto: Re: [epixa/tbyn] Broken paths when attempting to build, either 
that or README needs more than just npm install (#1)

**Comment by epixa** [comment]
@emudojo Ah, so it's a problem with this setup on windows.  If you figure out what the issue is on windows, I'd very much appreciate a PR.  I do want the dev environment to run on windows, but it isn't a big priority of mine at the moment.

**Comment by stephanfx** [comment]
Solved the issue to run on Windows with the following webpack.config.js file:
`var path = require('path');

module.exports = {
  context: path.resolve('src'),
  entry: {
    javascript: './index.js',
    html: './index.html',
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loaders: ['babel-loader'],
      },
      {
        test: /\.html$/,
        loader: 'file-loader?name=[name].[ext]',
      },
      {
        test: /\.css$/,
        loaders: ['style-loader', 'css-loader'],
      },
    ],
  },
  output: {
    filename: 'app.js',
    path: `${__dirname}/dist`,
  },
  resolve: {
    modulesDirectories: [
        path.resolve('node_modules'),
        path.resolve('src'),
        path.resolve('lib'),
    ],
    extensions: ['', '.webpack.js', '.web.js', '.js', '.jsx'],
  },
};`

**Comment by epixa** [comment]
@stephanfx If you submit a PR with that change, I'm happy to review it.  Otherwise I'll push path.resolve() changes next time I get a chance.

**Comment by stephanfx** [comment]
:) pull request submitted :)
